name: Revalidate data hari libur
on:
  schedule:
    - cron: '1 7 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
            fetch-depth: 0

    - name: revalidate
      run: |
        curl 'https://apiliburnasional.vercel.app/api/revalidate'